# Generated by Django 5.1.3 on 2024-11-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('anonymous', 'Anonymous'), ('registered', 'Registered'), ('staff', 'Staff'), ('superuser', 'Superuser')], max_length=50, null=True),
        ),
    ]
