# Generated by Django 5.1.3 on 2024-11-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('registered', 'Registered'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='registered', max_length=50),
        ),
    ]
