# Generated by Django 5.1.3 on 2024-11-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/login_bike.jpg', null=True, upload_to='event_images/'),
        ),
    ]
