name: Deploy Django to Render

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY:       ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_URL:            ${{ secrets.DATABASE_URL }}
      ALLOWED_HOSTS:           ${{ secrets.ALLOWED_HOSTS }}
      CLOUDINARY_CLOUD_NAME:   ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY:      ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET:   ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run Django tests
        run: |
          python manage.py test

      - name: ⚙️ Collect static files & run migrations
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate

      - name: 🚀 Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
