# Generated by Django 5.1.3 on 2024-12-07 13:59

import bike_connect.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the event (max 200 characters).', max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(help_text='Provide a detailed description of the event.', verbose_name='Event Description')),
                ('date', models.DateField(help_text='Specify the date when the event will take place.', verbose_name='Event Date')),
                ('location', models.CharField(help_text='Enter the location of the event (max 200 characters).', max_length=200, verbose_name='Event Location')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the event.', null=True, storage=bike_connect.storages.MediaStorage(), upload_to='events/', verbose_name='Event Image')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('cancelled', 'Cancelled')], default='joined', help_text="The user's participation status ('joined' or 'cancelled').", max_length=20, verbose_name='Participation Status')),
                ('comment', models.TextField(blank=True, help_text="Optional comment about the user's participation.", null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the participation was created.', verbose_name='Participation Created At')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
    ]
