# Generated by Django 5.1.3 on 2024-12-08 02:21

import bike_connect.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the event.', max_length=255, null=True, storage=bike_connect.storages.MediaStorage(), upload_to='events/', verbose_name='Event Image'),
        ),
    ]
