# Generated by Django 5.1.3 on 2024-12-09 00:59

import bike_connect.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the news article.', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=bike_connect.storages.MediaStorage(), upload_to='news_images/', verbose_name='Image'),
        ),
    ]
