# Generated by Django 5.1.3 on 2024-12-08 23:11

import bike_connect.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikepost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the post.', max_length=255, null=True, storage=bike_connect.storages.MediaStorage(), upload_to='bike_posts/', verbose_name='Post Image'),
        ),
    ]
