name: Deploy Django App to Render

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python cyclingnets/manage.py test

      - name: 🔧 Run migrations & collectstatic
        run: |
          python cyclingnets/manage.py migrate --noinput
          python cyclingnets/manage.py collectstatic --noinput
        env:
          DJANGO_SETTINGS_MODULE: cyclingnets.settings

      - name: Trigger Render Deploy Hook (optional)
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
